AWSTemplateFormatVersion: 2010-09-09
Parameters:
  vpc1securityGroupStackName: #ParameterKey
    Description: 'Name of your vpc1 Security Group CFN Stack'
    Type: String
    Default: 'vpc1-securitygroup'
  vpc1StackName: #ParameterKey
    Description: 'Name of your vpc1 CFN Stack'
    Type: String
    Default: 'vpc1'
Resources: 
  vpc1publicInstance1: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0d058fe428540cd89 #ubuntu 20.04 LTS
      InstanceType: t2.micro
      SubnetId:
        Fn::ImportValue:
          !Sub ${vpc1StackName}-publicSubnet1ID
      KeyName: todaykeypair
      Tags: 
        - Key: "Name"
          Value: "vpc1-public-instance-1"
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${vpc1securityGroupStackName}-vpc1SecurityGroupID
Outputs:
  vpc1publicInstanceDNS:
    Description: DNS Name of VPC1 Public Instance1
    Value: !GetAtt vpc1publicInstance1.PublicDnsName