AWSTemplateFormatVersion: 2010-09-09
Resources:
  mystratocloud:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: '172.16.0.0/16'
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: 'default'
      Tags: 
        - Key: 'Name'
          Value: 'mystratocloud-master-vpc2'
  vpc2publicSubnet1:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: 'ap-southeast-1a'
      CidrBlock: '172.16.1.0/24'
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: 'Name'
          Value: 'mastervpc2-public-subnet1'
      VpcId:
        !Ref mystratocloud
  vpc2publicSubnet2:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: 'ap-southeast-1b'
      CidrBlock: '172.16.2.0/24'
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: 'Name'
          Value: 'mastervpc2-public-subnet2'
      VpcId:
        !Ref mystratocloud
  vpc2publicSubnet3:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: 'ap-southeast-1c'
      CidrBlock: '172.16.3.0/24'
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: 'Name'
          Value: 'mastervpc2-public-subnet3'
      VpcId:
        !Ref mystratocloud
  vpc2routeTableForPublicSubnets:
    Type: AWS::EC2::RouteTable
    Properties: 
      Tags: 
        - Key: 'Name'
          Value: 'vpc2-route-table-publicSubnets'
      VpcId:
        !Ref mystratocloud
  # Associate publicSubnet1 to RouteTable
  publicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        !Ref vpc2publicSubnet1
      RouteTableId:
        !Ref vpc2routeTableForPublicSubnets
  # Associate publicSubnet1 to RouteTable
  publicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        !Ref vpc2publicSubnet2
      RouteTableId:
        !Ref vpc2routeTableForPublicSubnets
  # Associate publicSubnet1 to RouteTable
  publicSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        !Ref vpc2publicSubnet3
      RouteTableId:
        !Ref vpc2routeTableForPublicSubnets
  vpc2IGW:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key: 'Name'
          Value: 'vpc2 igw'
  attachVPCAndIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId:
        !Ref vpc2IGW
      VpcId:
        !Ref mystratocloud
  defaultRouteToIGW:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId:
        !Ref vpc2IGW
      RouteTableId:
        !Ref vpc2routeTableForPublicSubnets
Outputs:
  mystratocloudID: #logicalID
    Description: 'mystratocloud master vpc2 ID'
    Value:
      !Ref mystratocloud # the vaule of export is here
    Export:
      Name:
        !Sub ${AWS::StackName}-VPCID # the name of infra-stack export
  vpc2publicSubnet1ID: #logicalID
    Description: 'mystratocloud master vpc2 publicSubnet1 ID'
    Value:
      !Ref vpc2publicSubnet2 # the vaule of export is here
    Export:
      Name:
        !Sub ${AWS::StackName}-publicSubnet1ID # the name of infra-stack export
  vpc2publicSubnet2ID: #logicalID
    Description: 'mystratocloud master VPC publicSubnet2 ID'
    Value:
      !Ref vpc2publicSubnet2 # the vaule of export is here
    Export:
      Name:
        !Sub ${AWS::StackName}-publicSubnet2ID # the name of infra-stack export
  vpc2publicSubnet3ID: #logicalID
    Description: 'mystratocloud master VPC publicSubnet3 ID'
    Value:
      !Ref vpc2publicSubnet3 # the vaule of export is here
    Export:
      Name:
        !Sub ${AWS::StackName}-publicSubnet3ID # the name of infra-stack export
  vpc2routeTableForPublicSubnets: #logicalID
    Description: 'mystratocloud  routeTable ID'
    Value:
      !Ref vpc2routeTableForPublicSubnets # the vaule of export is here
    Export:
      Name:
        !Sub ${AWS::StackName}-routeTableID # the name of infra-stack export

  vpc2CidrBlock: #logicalID
    Description: 'mystratocloud CIDR'
    Value: !GetAtt mystratocloud.CidrBlock
    Export:
      Name:
        !Sub ${AWS::StackName}-vpc2CidrBlock 